export interface StripeTestCardItem {
  brand: string;
  label?: string;
  number: string;
  cvcRule: string;
  dateRule: string;
  description: string;
  docsUrl: string;
}

const STRIPE_TESTING_DOCS_URL = "https://docs.stripe.com/testing";

export const STRIPE_SUCCESS_TEST_CARDS: StripeTestCardItem[] = [
  {
    brand: "Visa",
    label: "Visa",
    number: "4242424242424242",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use for a standard successful card payment in Stripe test mode.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Visa",
    label: "Visa (debit)",
    number: "4000056655665556",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test Stripe flows with a Visa debit card.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Mastercard",
    label: "Mastercard",
    number: "5555555555554444",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to validate successful card flows for Mastercard in Stripe.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Mastercard",
    label: "Mastercard (2-series)",
    number: "2223003122003222",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test a successful payment with a 2-series Mastercard.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Mastercard",
    label: "Mastercard (debit)",
    number: "5200828282828210",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test Stripe flows with a Mastercard debit card.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Mastercard",
    label: "Mastercard (prepaid)",
    number: "5105105105105100",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test successful prepaid Mastercard payments.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "American Express",
    label: "American Express",
    number: "378282246310005",
    cvcRule: "Any 4 digits",
    dateRule: "Any future date",
    description: "Use to test Amex-specific form handling, including 4-digit CVC input.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "American Express",
    label: "American Express",
    number: "371449635398431",
    cvcRule: "Any 4 digits",
    dateRule: "Any future date",
    description: "Use as an alternative successful American Express test card.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Discover",
    label: "Discover",
    number: "6011111111111117",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to confirm Discover brand support in Stripe checkout flows.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Discover",
    label: "Discover",
    number: "6011000990139424",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use as an alternate successful Discover test card.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Discover",
    label: "Discover (debit)",
    number: "6011981111111113",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test successful Discover debit card payments.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Diners Club",
    label: "Diners Club",
    number: "3056930009020004",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to simulate a successful Diners Club payment.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "Diners Club",
    label: "Diners Club (14-digit card)",
    number: "36227206271667",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test a successful 14-digit Diners Club card flow.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "BCcard and DinaCard",
    label: "BCcard and DinaCard",
    number: "6555900000604105",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test a successful BCcard or DinaCard payment.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "JCB",
    label: "JCB",
    number: "3566002020360505",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to validate successful JCB card support in Stripe.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "UnionPay",
    label: "UnionPay",
    number: "6200000000000005",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test a successful UnionPay card payment.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "UnionPay",
    label: "UnionPay (debit)",
    number: "6200000000000047",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test successful UnionPay debit card flows.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
  {
    brand: "UnionPay",
    label: "UnionPay (19-digit card)",
    number: "6205500000000000004",
    cvcRule: "Any 3 digits",
    dateRule: "Any future date",
    description: "Use to test a successful 19-digit UnionPay card flow.",
    docsUrl: STRIPE_TESTING_DOCS_URL,
  },
];
